Created slugs to be used in other project
AgoraIO/app-builder-backend pull request #16
Opened 2022-01-18 09:44 UTC by girishg4t

1) this script will create slugs which can be used to use in other project like console

2022-01-18 11:18 UTC, samyak-jain requested changes

2022-01-18 11:18 UTC, samyak-jain commented on scripts/create_slugs.sh
> +tar czfv appBuilderCore.tgz ./appBuilderCore
We should first move the binary in a folder called ```app``` and then compress that folder into the tarball based on the instructions: https://devcenter.heroku.com/articles/platform-api-deploying-slugs#create-slug-archive. IIRC, heroku will just ignore any folder not named app.

2022-01-18 12:14 UTC, girishg4t commented on scripts/create_slugs.sh
> +tar czfv appBuilderCore.tgz ./appBuilderCore
done

2022-01-20 05:19 UTC, samyak-jain approved these changes

2022-01-20 05:20 UTC, merged